name: LFEcatalog
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - jupyter
  - jupyterlab
  - notebook
  - obspy
  - pandas
  - scikit-learn
  - matplotlib
  - numpy<1.17
  - scipy
