name: CronJob

on:
  schedule:
#    - cron: '0 0 * * *' # Daily at midnight
#    - cron: '0 * * * *' #On the hour
    - cron: '*/5 * * * *' #Every 5 minutes for testing

jobs:
  cronjob:
    runs-on: ubuntu-18.04
    steps:
      - name: Set Job Environment Variables
        run: |
          DATE="$( date -u -d '3 days ago' '+%Y%m%d' )"
          echo "::set-env name=DATE::${DATE}"

      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Setup Conda Environment
        uses: goanpeca/setup-miniconda@v1
        with:
           environment-file: environment.yml
           activate-environment: lfelib
           miniconda-version: 'latest'
           auto-activate-base: false
           auto-update-conda: false

      # Later change to versioned release on pypi
      - name: Install lfelib
        shell: bash -l {0}
        run: |
          pip install --extra-index-url https://test.pypi.org/simple/ lfelib

      - name: Run Daily Processing
        shell: bash -l {0}
        run: |
          cd examples
          #./cronscript.sh

          # Simple commands to test
          mkdir LFEs
          echo "A Test File" > results.csv

      # NOTE: artiface "name": cannot contain '\', '/', "', ':', '<', '>', '|', '*', and '?'
      # Single file save
      #- name: Upload 080326.08.015 Results CSV
      #  uses: actions/upload-artifact@v1
      #  with:
      #    name: 080326.08.015_${{env.DATE}}_000000.csv
      #    path: ./examples/LFEs/080326.08.015/catalog_${{env.DATE}}_000000.csv

      - name: Upload Zipped LFEs Folder with Results
        uses: actions/upload-artifact@v1
        with:
          name: ${{env.DATE}}
          path: ./examples/LFEs/

      - name: Upload Results CSVs to Google Drive
        uses: wei/rclone@v1
        env:
          RCLONE_CONFIG_INCUBATOR_TOKEN: ${{ secrets.RCLONE_CONFIG_INCUBATOR_TOKEN }}
          RCLONE_CONFIG_INCUBATOR_TEAM_DRIVE: ${{secrets.RCLONE_CONFIG_INCUBATOR_TEAM_DRIVE }}
          RCLONE_CONFIG_INCUBATOR_TYPE: drive
          RCLONE_CONFIG_INCUBATOR_SCOPE: drive
        with:
          args: copy ./examples/LFEs/ incubator:lfelib/cronjob
