name: CronJob

on:
  schedule:
#    - cron: '0 0 * * *' # Daily at midnight
    - cron: '*/5 * * * *' #Every 5 minutes for testing

jobs:
  cronjob:
    runs-on: ubuntu-18.04
    steps:
      - name: Set Job Environment Variables
        run: |
          DATE="$( date -u -d '3 days ago' '+%Y%m%d' )"
          echo "::set-env name=DATE::${DATE}"

      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Setup Conda Environment
        uses: goanpeca/setup-miniconda@v1
        with:
           environment-file: environment.yml
           activate-environment: lfelib
           miniconda-version: 'latest'
           auto-activate-base: false
           auto-update-conda: false

      # Later change to versioned release on pypi
      - name: Install lfelib
        shell: bash -l {0}
        run: |
          pip install git+git://github.com/ArianeDucellier/Incubator2020

      - name: Run Daily Processing
        shell: bash -l {0}
        run: |
          cd examples
          ./cronscript.sh

      # NOTE: artiface "name": cannot contain '\', '/', "', ':', '<', '>', '|', '*', and '?'
      - name: Upload 080326.08.015 Results CSV
        uses: actions/upload-artifact@v1
        with:
          name: 080326.08.015_${{env.DATE}}_000000.csv
          path: ./examples/LFEs/080326.08.015/catalog_${{env.DATE}}_000000.csv

      - name: Upload 080421.14.048 Results CSV
        uses: actions/upload-artifact@v1
        with:
          name: 080421.14.048_${{env.DATE}}_000000.csv
          path: ./examples/LFEs/080421.14.048/catalog_${{env.DATE}}_000000.csv
